const data = {
    usuarios: [
        {
            id: 1,
            email: 'pablo@gmail.com',
            clave: 'pablo',
            nombreUsuario: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            fecha: '15/12/1865',
            dni: '44986213'
        },

        {
            id: 2,
            email: 'maria@gmail.com',
            clave: 'maria',
            nombreUsuario: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            fecha: '20/09/2002',
            dni: '42871032'
        },

        {
            id: 3,
            email: 'martin@gmail.com',
            clave: 'martin',
            nombreUsuario: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            fecha: '16/07/1924',
            dni: '78951468'
        },

        {
            id: 4,
            email: 'paula@gmail.com',
            clave: 'paula',
            nombreUsuario: 'Paula',
            fotoPerfil: '/img/paula.jpg',
            fecha: '28/10/1970',
            dni: '45236987'
        },

        {
            id: 5,
            email: 'franco@gmail.com',
            clave: 'franco',
            nombreUsuario: 'Franco',
            fotoPerfil: '/img/franco.jpg',
            fecha: '03/03/2003',
            dni: '46257465'
        },

        {
            id: 6,
            email: 'lola@gmail.com',
            clave: 'lola',
            nombreUsuario: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            fecha: '30/12/1999',
            dni: '40458965'
        },

        {
            id: 7,
            email: 'tomas@gmail.com',
            clave: 'tomas',
            nombreUsuario: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            fecha: '19/10/2005',
            dni: '48987201'
        },

        {
            id: 8,
            email: 'magui@gmail.com',
            clave: 'magui',
            nombreUsuario: 'Magui',
            fotoPerfil: '/img/magui.jpg',
            fecha: '20/12/1975',
            dni: '22659874'
        },

        {
            id: 9,
            email: 'raul@gmail.com',
            clave: 'raul',
            nombreUsuario: 'Raul',
            fotoPerfil: '/img/raul.jpg',
            fecha: '08/11/2001',
            dni: '43598712'
        },

        {
            id: 10,
            email: 'emma@gmail.com',
            clave: 'emma',
            nombreUsuario: 'Emma',
            fotoPerfil: '/img/emma.jpg',
            fecha: '18/08/1980',
            dni: '38965417'
        },
    ],
    posteos: [{
        id: 1,
        clienteid: 1,
        nombreUsuario: 'Pablo',
        fotoPerfil: '/img/pablo.jpg',
        nombreImg: "https://cdn.motor1.com/images/mgl/Akkwn2/s1/lanzamiento-mercedes-benz-clasec-1.jpg",
        textonombre: "mercedez benz",
        textoposteo: "color negro",
        comentarios: [{
            id: 1,
            idPost: 1,
            idUsuario: 2,
            nombre: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            textoComentario: "Muy bueno" ,
        },
        {
            id: 2,
            idPost: 1,
            idUsuario: 3,
            nombre: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            textoComentario: "No me gusto" ,
        },
        {
            id: 3,
            idPost: 1,
            idUsuario: 4,
            nombre: 'Paula',
            fotoPerfil: '/img/paula.jpg',
            textoComentario: "Esplendido" ,
        },
        {
            id: 4,
            idPost: 1,
            idUsuario: 5,
            nombre: 'Franco',
            fotoPerfil: '/img/franco.jpg',
            textoComentario: "Buenisimo" ,
        },
    ]
    },
    {
        id: 2,
        clienteid: 2,
        nombreUsuario: 'Maria',
        fotoPerfil: '/img/maria.jpg',
        nombreImg: "https://media.autoexpress.co.uk/image/private/s--5-xtWGFv--/f_auto,t_content-image-full-desktop@1/v1636372558/autoexpress/2021/11/Ferrari%20812%20Competizione%202021-2.jpg",
        textonombre: "Lago di Como",
        textoposteo: "te paso a buscar en la amarilla?bbeta",
        comentarios: [{
            id: 1,
            idPost: 2,
            idUsuario: 10,
            nombre: 'Emma',
            fotoPerfil: '/img/emma.jpg',
            textoComentario: "Que lindo lugar" ,
        },
        {
            id: 2,
            idPost: 2,
            idUsuario: 9,
            nombre: 'Raul',
            fotoPerfil: '/img/raul.jpg',
            textoComentario: "Italia" ,
        },
        {
            id: 3,
            idPost: 2,
            idUsuario: 8,
            nombre: 'Magui',
            fotoPerfil: '/img/magui.jpg',
            textoComentario: "Europa es god" ,
        },
        {
            id: 4,
            idPost: 2,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "LLevame!" ,
        }
    ]
    },
    {
        id: 3,
        clienteid: 7,
        nombreUsuario: 'Tomas',
        fotoPerfil: '/img/tomas.jpg',
        nombreImg: 'https://www.km77.com/media/fotos/volkswagen_golf_2009_gti_3141_1.jpg',
        textonombre: "Messi",
        textoposteo: "Golf gti",
        comentarios: [{
            id: 1,
            idPost: 3,
            idUsuario: 6,
            nombre: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            textoComentario: "Aguante messiii" ,
        },
        {
            id: 2,
            idPost: 3,
            idUsuario: 5,
            nombre: 'Franco',
            fotoPerfil: '/img/franco.jpg',
            textoComentario: "vamooosss" ,
        },
        {
            id: 3,
            idPost: 3,
            idUsuario: 8,
            nombre: 'Magui',
            fotoPerfil: '/img/magui.jpg',
            textoComentario: "goat " ,
        },
        {
            id: 4,
            idPost: 3,
            idUsuario: 4,
            nombre: 'Paula',
            fotoPerfil: '/img/paula.jpg',
            textoComentario: "indiscutido!" ,
        }
    ]
    },
    {
        id: 4,
        clienteid: 3,
        nombreUsuario: 'Martin',
        fotoPerfil: '/img/martin.jpg',
        nombreImg: "https://cdn.motor1.com/images/mgl/VRW87/s1/primicia-confirmada-vw-presento-la-amarok-v6.webp",
        textonombre: "Asado",
        textoposteo: "Amarokr",
        comentarios: [{
            id: 1,
            idPost: 4,
            idUsuario: 1,
            nombre: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            textoComentario: "Que rico" ,
        },
        {
            id: 2,
            idPost: 4,
            idUsuario: 9,
            nombre: 'Raul',
            fotoPerfil: '/img/raul.jpg',
            textoComentario: "Prefiero el vacio!!" ,
        },
        {
            id: 3,
            idPost: 4,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "Invitame mal amigo " ,
        },
        {
            id: 4,
            idPost: 4,
            idUsuario: 10,
            nombre: 'Emma',
            fotoPerfil: '/img/emma.jpg',
            textoComentario: "El mejor corte lejos" ,
        }
    ]
    },
    {
        id: 5,
        clienteid: 6,
        nombreUsuario: 'Lola',
        fotoPerfil: '/img/lola.jpg',
        nombreImg: "https://cdn.autobild.es/sites/navi.axelspringer.es/public/media/image/2022/10/bmw-m2-coupe-2023-2839887.jpg?tf=2048x",
        textonombre: "Pareja",
        textoposteo: "Mi pareja",
        comentarios: [{
            id: 1,
            idPost: 5,
            idUsuario: 1,
            nombre: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            textoComentario: "Les mando un abrazo" ,
        },
        {
            id: 2,
            idPost: 5,
            idUsuario: 4,
            nombre: 'Paula',
            fotoPerfil: '/img/paula.jpg',
            textoComentario: "A mi me dejaron" ,
        },
        {
            id: 3,
            idPost: 5,
            idUsuario: 5,
            nombre: 'Franco',
            fotoPerfil: '/img/franco.jpg',
            textoComentario: "Paula yo te propongo matrimonio no hay drama" ,
        },
        {
            id: 4,
            idPost: 5,
            idUsuario: 2,
            nombre: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            textoComentario: "Que tiernos" ,
        }
    ]
    },
    {
        id: 6,
        clienteid: 10,
        nombreUsuario: 'Emma',
        fotoPerfil: '/img/emma.jpg',
        nombreImg: "https://cdn.motor1.com/images/mgl/2NO9Xp/s1/lamborghini-urus-by-mansory-and-mtm.webp",
        textonombre: "lamborghini",
        textoposteo: "Que buena pelicula",
        comentarios: [{
            id: 1,
            idPost: 6,
            idUsuario: 2,
            nombre: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            textoComentario: "No la entiendo" ,
        },
        {
            id: 2,
            idPost: 6,
            idUsuario: 9,
            nombre: 'Raul',
            fotoPerfil: '/img/raul.jpg',
            textoComentario: "Nolan crack" ,
        },
        {
            id: 3,
            idPost: 6,
            idUsuario: 3,
            nombre: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            textoComentario: "Tarantino es mejor" ,
        },
        {
            id: 4,
            idPost: 6,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "Aburrida" ,
        }
    ]
    },
    {
        id: 7,
        clienteid: 8,
        nombreUsuario: 'Magui',
        fotoPerfil: '/img/magui.jpg',
        nombreImg: "https://www.digitaltrends.com/wp-content/uploads/2019/01/lamborghini_huracan_evo_street_2.jpg?resize=625%2C417&p=1",
        textonombre: "Receta",
        textoposteo: "Miren esta receta",
        comentarios: [{
            id: 1,
            idPost: 7,
            idUsuario: 5,
            nombre: 'Franco',
            fotoPerfil: '/img/franco.jpg',
            textoComentario: "Prefiero el pesto" ,
        },
        {
            id: 2,
            idPost: 7,
            idUsuario: 3,
            nombre: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            textoComentario: "Cuando me cocinas?" ,
        },
        {
            id: 3,
            idPost: 7,
            idUsuario: 2,
            nombre: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            textoComentario: "Bolognesaaa" ,
        },
        {
            id: 4,
            idPost: 7,
            idUsuario: 6,
            nombre: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            textoComentario: "Fideo con salsa" ,
        }
    ]
    },
    {
        id: 8,
        clienteid: 5,
        nombreUsuario: 'Franco',
        fotoPerfil: '/img/franco.jpg',
        nombreImg: "https://images.dealer.com/autodata/us/640/color/2023/USD30MBS231A0/040.jpg",
        textonombre: "mercho",
        textoposteo: "Mejor tenista del mundo",
        comentarios: [{
            id: 1,
            idPost: 8,
            idUsuario: 1,
            nombre: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            textoComentario: "Asi es" ,
        },
        {
            id: 2,
            idPost: 8,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "Sin dudas" ,
        },
        {
            id: 3,
            idPost: 8,
            idUsuario: 2,
            nombre: 'Maria',
            fotoPerfil: '/img/maria.jpg',
            textoComentario: "Epico" ,
        },
        {
            id: 4,
            idPost: 8,
            idUsuario: 6,
            nombre: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            textoComentario: "Nadal es mejor" ,
        }
    ]
    },
    {
        id: 9,
        clienteid: 9,
        nombreUsuario: 'Raul',
        fotoPerfil: '/img/raul.jpg',
        nombreImg: "https://autodinamico.mx/wp-content/uploads/2022/04/AMG-AD1-1920x1080.jpg",
        textonombre: "MassaMilei",
        textoposteo: "Quien gana?",
        comentarios: [{
            id: 1,
            idPost: 9,
            idUsuario: 1,
            nombre: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            textoComentario: "Massa" ,
        },
        {
            id: 2,
            idPost: 9,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "Milei" ,
        },
        {
            id: 3,
            idPost: 9,
            idUsuario: 3,
            nombre: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            textoComentario: "Todos" ,
        },
        {
            id: 4,
            idPost: 9,
            idUsuario: 6,
            nombre: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            textoComentario: "Ninguno" ,
        }
    ]
    },
    {
        id: 10,
        clienteid: 4,
        nombreUsuario: 'Paula',
        fotoPerfil: '/img/paula.jpg',
        nombreImg: "https://gagadget.com/media/cache/df/34/df34d87e1d252e5c9d5a3694ceb0de68.jpg",
        textonombre: "Paretto",
        textoposteo: "Foto mia paula paretto",
        comentarios: [{
            id: 1,
            idPost: 10,
            idUsuario: 1,
            nombre: 'Pablo',
            fotoPerfil: '/img/pablo.jpg',
            textoComentario: "Que grande paula!" ,
        },
        {
            id: 2,
            idPost: 10,
            idUsuario: 7,
            nombre: 'Tomas',
            fotoPerfil: '/img/tomas.jpg',
            textoComentario: "Felicitaciones" ,
        },
        {
            id: 3,
            idPost: 10,
            idUsuario: 3,
            nombre: 'Martin',
            fotoPerfil: '/img/martin.jpg',
            textoComentario: "Sos crack" ,
        },
        {
            id: 4,
            idPost: 10,
            idUsuario: 6,
            nombre: 'Lola',
            fotoPerfil: '/img/lola.jpg',
            textoComentario: "Bien ahi" ,
        }
    ]
    },
    ]}

    module.exports = data